namespace SharewoodAPI;

public enum ESharewoodSubCategory {
  None = 0,
  VideoFilms = 9,
  VideoSeries = 10,
  VideoFilmsAnimation = 11,
  VideoSeriesAnimation = 12,
  VideoDocumentaires = 13,
  VideoEmissionTV = 14,
  VideoSpectacles = 15,
  VideoSports = 16,
  VideoKaraoke = 17,
  AudioKaraoke = 18,
  AudioMusique = 20,
  AudioPodcast = 21,
  AudioSamples = 22,
  AudioEBooks = 23,
  EbooksBDs = 24,
  EbooksComics = 25,
  EbooksManga = 26,
  EbooksLivres = 27,
  EbooksPresse = 28,
  ApplicationLinux = 29,
  ApplicationWindows = 30,
  ApplicationMac = 31,
  ApplicationMobile = 34,
  ApplicationGPS = 35,
  JeuxVideoLinux = 36
}
