global using BLTools.Core;
global using BLTools.Core.Logging;
global using BLTools.Core.Diagnostic;
global using BLTools.Core.Text;
global using System;
global using System.Net;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;